/**
 * Regenerates src/lib/phone-countries.ts — the country list for the phone
 * picker (flag, dial code, English + Vietnamese names).
 *
 * Run:  npx tsx scripts/generate-phone-countries.ts
 *
 * The list is generated ahead of time so the browser doesn't have to download
 * libphonenumber's metadata just to show a dropdown.
 */
import { writeFileSync } from "node:fs";
import { getCountries, getCountryCallingCode } from "libphonenumber-js";

const en = new Intl.DisplayNames(["en"], { type: "region" });
const vi = new Intl.DisplayNames(["vi"], { type: "region" });

const rows = getCountries()
  .map((iso) => ({
    iso,
    dial: getCountryCallingCode(iso),
    name: en.of(iso) ?? iso,
    nameVi: vi.of(iso) ?? iso,
  }))
  // Skip territories Intl can't name (it just echoes the code back).
  .filter((c) => c.name !== c.iso)
  .sort((a, b) => a.name.localeCompare(b.name, "en"));

const body = rows
  .map((c) => `  [${JSON.stringify(c.iso)}, ${JSON.stringify(c.dial)}, ${JSON.stringify(c.name)}, ${JSON.stringify(c.nameVi)}],`)
  .join("\n");

const file = `// GENERATED by scripts/generate-phone-countries.ts — do not edit by hand.
// [ISO code, dial code, English name, Vietnamese name]
export const PHONE_COUNTRY_ROWS: ReadonlyArray<readonly [string, string, string, string]> = [
${body}
];
`;

writeFileSync("src/lib/phone-countries.ts", file);
console.log(`Wrote ${rows.length} countries to src/lib/phone-countries.ts`);
